# Generated by Django 5.2.17 on 2026-09-11 19:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('artist_minimum_approved', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_closing',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(max_length=80)),
                ('client_name', models.CharField(max_length=160)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
