# Generated by Django 5.2.17 on 2026-09-11 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0002_alter_guest_status_alter_guestproposal_status'),
        ('sales', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closing', to='scheduling.appointment'),
        ),
        migrations.AddField(
            model_name='closing',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='closing',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closing', to='sales.lead'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('guest', 'external_reference'), name='uq_lead_guest_external_reference'),
        ),
    ]
