# Generated by Django 5.2.17 on 2026-09-11 18:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(default=list)),
                ('offers_accommodation', models.BooleanField(default=False)),
                ('accommodation_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('UNDER_REVIEW', 'Em análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado'), ('INACTIVE', 'Inativo')], default='DRAFT', max_length=24)),
                ('review_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_studios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studios_studio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudioBookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.UUIDField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('ACCEPTED', 'Aceita'), ('DECLINED', 'Recusada'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='REQUESTED', max_length=20)),
                ('response_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artists.artistprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='studios.studio')),
            ],
            options={
                'db_table': 'studios_booking_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')], default='PENDING', max_length=12)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='studios.studiobookingrequest')),
            ],
            options={
                'db_table': 'studios_booking',
            },
        ),
        migrations.CreateModel(
            name='StudioPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pricing_type', models.CharField(choices=[('HOURLY', 'Hora'), ('DAILY', 'Diária'), ('WEEKLY', 'Semana'), ('PERCENTAGE', 'Percentual'), ('NEGOTIATED', 'Negociado')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('conditions', models.TextField(blank=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='studios.studio')),
            ],
            options={
                'db_table': 'studios_price',
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='studios.studio')),
            ],
            options={
                'db_table': 'studios_workstation',
            },
        ),
        migrations.CreateModel(
            name='StudioAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('timezone', models.CharField(max_length=64)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='studios.studio')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studios.workstation')),
            ],
            options={
                'db_table': 'studios_availability',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.UniqueConstraint(fields=('studio', 'name'), name='uq_studio_station'),
        ),
    ]
