# Generated by Django 5.2.17 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_link_booking_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=24),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='studiobookingrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='studioprice',
            name='pricing_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('PERCENTAGE', 'Percentage'), ('NEGOTIATED', 'Negotiated')], max_length=20),
        ),
    ]
