# Generated by Django 5.2.17 on 2026-09-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0003_alter_studio_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiobookingrequest",
            name="workstation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_requests",
                to="studios.workstation",
            ),
        ),
    ]
