# Generated by Django 5.2.17 on 2026-09-11 18:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CAPTURING', 'Em captação'), ('FULLY_BOOKED', 'Agenda completa'), ('IN_PROGRESS', 'Em andamento'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='CAPTURING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artists.artistprofile')),
            ],
            options={
                'db_table': 'guests_guest',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='GuestGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occupancy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('revenue_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='guests.guest')),
            ],
            options={
                'db_table': 'guests_goal',
            },
        ),
        migrations.CreateModel(
            name='GuestProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('ads_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_tattoo_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_ticket', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_session_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PLANNING', 'Em planejamento'), ('READY', 'Pronta para confirmação'), ('CONFIRMED', 'Confirmada'), ('DECLINED', 'Recusada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artists.artistprofile')),
                ('primary_studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studios.studio')),
            ],
            options={
                'db_table': 'guests_proposal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='guests.guestproposal'),
        ),
        migrations.CreateModel(
            name='GuestStudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='guests.guest')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studios.studio')),
            ],
            options={
                'db_table': 'guests_guest_studio',
                'ordering': ['starts_at'],
            },
        ),
    ]
