# Generated by Django 5.2.17 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('CAPTURING', 'Capturing leads'), ('FULLY_BOOKED', 'Fully booked'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='CAPTURING', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestproposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNING', 'Planning'), ('READY', 'Ready for confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
