# Generated by Django 5.2.17 on 2026-09-11 19:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_alter_artistapplication_status'),
        ('guests', '0002_alter_guest_status_alter_guestproposal_status'),
        ('studios', '0003_alter_studio_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=160)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLATION_REQUESTED', 'Cancellation requested'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artists.artistprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='guests.guest')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studios.studio')),
            ],
            options={
                'db_table': 'scheduling_appointment',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsibility', models.CharField(choices=[('ARTIST', 'Artist')], default='ARTIST', max_length=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='scheduling.appointment')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_cancellation_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['artist', 'starts_at', 'ends_at'], name='scheduling__artist__4785c4_idx'),
        ),
    ]
