# Generated by Django 5.2.17 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('STUDIO', 'Studio'), ('ADVISORY', 'Advisory')], max_length=24, unique=True),
        ),
    ]
