# Generated by Django 5.2.17 on 2026-09-11 19:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('external_reference', models.CharField(max_length=160)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=16)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_agency_receipt',
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('AGENCY_REVENUE', 'Agency revenue'), ('ARTIST_RECEIVABLE', 'Artist receivable'), ('ARTIST_REFUND_DUE', 'Artist refund due')], max_length=24)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('EXPECTED', 'Expected'), ('DUE', 'Due')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('source_reference', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_financial_entry',
                'ordering': ['created_at'],
            },
        ),
    ]
