# Generated by Django 5.2.17 on 2026-09-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('guests', '0002_alter_guest_status_alter_guestproposal_status'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyreceipt',
            name='closing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agency_receipt', to='sales.closing'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='sales.closing'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='guests.guest'),
        ),
        migrations.AddConstraint(
            model_name='financialentry',
            constraint=models.UniqueConstraint(fields=('entry_type', 'source_reference'), name='uq_financial_entry_type_source'),
        ),
    ]
