# Generated by Django 5.2.17 on 2026-09-12 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artistapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPortfolioUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('style', models.CharField(blank=True, max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artists_pending_portfolio_upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
