# Generated by Django 5.2.17 on 2026-09-12 00:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0002_alter_guest_status_alter_guestproposal_status'),
        ('studios', '0003_alter_studio_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(max_length=300)),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('booking_reference', models.CharField(blank=True, max_length=160)),
                ('private_document_key', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodations', to='guests.guest')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_accommodations', to='studios.studio')),
            ],
            options={
                'db_table': 'logistics_accommodation',
                'ordering': ['check_in_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_type', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('RETURN', 'Return'), ('OTHER', 'Other')], max_length=12)),
                ('origin', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=160)),
                ('departs_at', models.DateTimeField()),
                ('arrives_at', models.DateTimeField()),
                ('origin_timezone', models.CharField(max_length=64)),
                ('destination_timezone', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('booking_reference', models.CharField(blank=True, max_length=160)),
                ('private_document_key', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_segments', to='guests.guest')),
            ],
            options={
                'db_table': 'logistics_travel_segment',
                'ordering': ['departs_at'],
            },
        ),
    ]
